IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '404webpagedb')
BEGIN
    PRINT 'Creando base de datos 404webpagedb...';
    CREATE DATABASE [404webpagedb];
END
ELSE
BEGIN
    PRINT 'La base de datos ya existe.';
END
GO

USE [404webpagedb];
GO

------------------------------------------------------------
-- TABLAS
------------------------------------------------------------
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_ARCHIVOS_BIBLIA')
CREATE TABLE DAT_ARCHIVOS_BIBLIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MOVIMIENTO INT,
    ARCHIVO INT,
    UBICACION NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_LIBROS_BIBLIA')
CREATE TABLE CAT_LIBROS_BIBLIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LIBRO INT,
    NOMBRE NVARCHAR(50),
    ABREVIATURA NVARCHAR(10),
    CAPITULOS INT
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_APRENDIZAJE_BIBLIA')
CREATE TABLE DAT_APRENDIZAJE_BIBLIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_ID INT,
    LIBRO_ID INT,
    CAPITULO INT,
    VERSICULO_INICIO INT,
    VERSICULO_FIN INT,
    MODULO INT,
    TEXTO NVARCHAR(MAX)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_CONCEPTOS_FINANZAS')
CREATE TABLE CAT_CONCEPTOS_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CONCEPTO NVARCHAR(50),
    FACTOR INT
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_MOVIMIENTOS_FINANZAS')
CREATE TABLE DAT_MOVIMIENTOS_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_MOVIMIENTO INT,
    CONCEPTO_ID INT,
    PROVEEDOR_ID INT,
    FECHA DATE,
    MODULO INT,
    IMPORTE MONEY
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_PROVEEDORES_FINANZAS')
CREATE TABLE CAT_PROVEEDORES_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_ARCHIVOS_FINANZAS')
CREATE TABLE DAT_ARCHIVOS_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MOVIMIENTO INT,
    ARCHIVO INT,
    UBICACION NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_ARCHIVOS_MEDICO')
CREATE TABLE DAT_ARCHIVOS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MOVIMIENTO INT,
    ARCHIVO INT,
    UBICACION NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_CONSULTAS_MEDICO')
CREATE TABLE DAT_CONSULTAS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FECHA DATE,
    MODULO_ID INT,
    EVENTO INT,
    IMPORTANCIA INT,
    UNIDAD_MEDICA INT,
    MEDICO INT,
    OBSERVACIONES NVARCHAR(MAX)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_EVENTOS_MEDICO')
CREATE TABLE CAT_EVENTOS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EVENTO NVARCHAR(50)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_IMPORTANCIA_MEDICO')
CREATE TABLE CAT_IMPORTANCIA_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IMPORTANCIA NVARCHAR(50)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_CLINICAS_MEDICO')
CREATE TABLE CAT_CLINICAS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UNIDAD_MEDICA NVARCHAR(50)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_MEDICAMENTOS_MEDICO')
CREATE TABLE CAT_MEDICAMENTOS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MEDICAMENTO NVARCHAR(150)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_MEDICAMENTOS_MEDICO')
CREATE TABLE DAT_MEDICAMENTOS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CONSULTA INT,
    MEDICAMENTO INT
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_MEDICOS_MEDICO')
CREATE TABLE CAT_MEDICOS_MEDICO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_TIPOS')
CREATE TABLE CAT_TIPOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO NVARCHAR(100),
    CATEGORIA INT
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_MODULOS')
CREATE TABLE CAT_MODULOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MODULO NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_CAT')
CREATE TABLE CAT_CAT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORIA NVARCHAR(100),
    MODULO INT
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAT_ARCHIVO_TIPO')
CREATE TABLE CAT_ARCHIVO_TIPO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_ARCHIVO NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_FINANZAS')
CREATE TABLE DAT_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MODULO_ID INT,
	ESTATUS NVARCHAR(100),
	MOVIMIENTO_ID INT,
	PROVEEDOR_ID INT,
	CONCEPTO_ID INT,
	FECHA DATE,
	IMPORTE MONEY,
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_DESGLOSE_FINANZAS')
CREATE TABLE DAT_DESGLOSE_FINANZAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FINANZA_ID INT,
    ELEMENTO NVARCHAR(100),
    CANTIDAD NUMERIC(18,3),
    PRECIO MONEY,
    

);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BIBLIA')
CREATE TABLE BIBLIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LibroNum INT,
    Capitulo INT,
    Versiculo INT,
    Texto NVARCHAR(MAX)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEMPORAL_DAT_BIBLIA')
CREATE TABLE TEMPORAL_DAT_BIBLIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_ID INT,
    LIBRO_ID INT,
    CAPITULO INT,
    VERSICULO_INICIO INT,
    VERSICULO_FIN INT,
    MODULO INT,
    TEXTO NVARCHAR(MAX)
);
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_ARCHIVOS_PERSONAL')
CREATE TABLE DAT_ARCHIVOS_PERSONAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EVENTO INT,
    ARCHIVO INT,
    UBICACION NVARCHAR(100)
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_DETALLES_ARCHIVOS_PERSONAL')
CREATE TABLE DAT_DETALLES_ARCHIVOS_PERSONAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MEDIA_ID INT,
    TITULO NVARCHAR(50),
    PERSONAS NVARCHAR(100),
    LUGAR NVARCHAR(100),
    FECHA DATE,
    HORA TIME,
    DESCRIPCION NVARCHAR(MAX)

);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_DETALLES_EVENTOS_PERSONAL')
CREATE TABLE DAT_DETALLES_EVENTOS_PERSONAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EVENTO_ID INT,
    TITULO NVARCHAR(50),
    CONTENIDO NVARCHAR(MAX)
);
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DAT_EVENTOS_PERSONAL')
CREATE TABLE DAT_EVENTOS_PERSONAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_ID INT,
    MODULO_ID INT,
    LUGAR NVARCHAR(100),
    FECHA DATE,
    HORA TIME,
    DESCRIPCION NVARCHAR(MAX),
    OBSERVACIONES NVARCHAR(MAX)
);
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_25')
ALTER TABLE DAT_DETALLES_ARCHIVOS_PERSONAL
ADD CONSTRAINT FK_25 FOREIGN KEY (MEDIA_ID) REFERENCES DAT_ARCHIVOS_PERSONAL(ID);
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_26')
ALTER TABLE DAT_ARCHIVOS_PERSONAL
ADD CONSTRAINT FK_26 FOREIGN KEY (EVENTO) REFERENCES DAT_EVENTOS_PERSONAL(ID);
GO

------------------------------------------------------------
-- RELACIONES (FOREIGN KEYS)
------------------------------------------------------------

-- DAT_APRENDIZAJE_BIBLIA → CAT_LIBROS_BIBLIA
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_1')
ALTER TABLE DAT_APRENDIZAJE_BIBLIA
ADD CONSTRAINT FK_1 FOREIGN KEY (LIBRO_ID) REFERENCES CAT_LIBROS_BIBLIA(ID);
GO

-- DAT_MOVIMIENTOS_FINANZAS → CAT_PROVEEDORES_FINANZAS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_2')
ALTER TABLE DAT_MOVIMIENTOS_FINANZAS
ADD CONSTRAINT FK_2 FOREIGN KEY (PROVEEDOR_ID) REFERENCES CAT_PROVEEDORES_FINANZAS(ID);
GO

-- DAT_MEDICAMENTOS_MEDICO → CAT_MEDICAMENTOS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_3')
ALTER TABLE DAT_MEDICAMENTOS_MEDICO
ADD CONSTRAINT FK_3 FOREIGN KEY (MEDICAMENTO) REFERENCES CAT_MEDICAMENTOS_MEDICO(ID);
GO

-- DAT_CONSULTAS_MEDICO → CAT_MEDICOS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_4')
ALTER TABLE DAT_CONSULTAS_MEDICO
ADD CONSTRAINT FK_4 FOREIGN KEY (MEDICO) REFERENCES CAT_MEDICOS_MEDICO(ID);
GO

-- DAT_APRENDIZAJE_BIBLIA → CAT_MODULOS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_5')
ALTER TABLE DAT_APRENDIZAJE_BIBLIA
ADD CONSTRAINT FK_5 FOREIGN KEY (MODULO) REFERENCES CAT_MODULOS(ID);
GO

-- DAT_APRENDIZAJE_BIBLIA → CAT_TIPOS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_6')
ALTER TABLE DAT_APRENDIZAJE_BIBLIA
ADD CONSTRAINT FK_6 FOREIGN KEY (TIPO_ID) REFERENCES CAT_TIPOS(ID);
GO

-- DAT_ARCHIVOS_BIBLIA → CAT_ARCHIVO_TIPO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_7')
ALTER TABLE DAT_ARCHIVOS_BIBLIA
ADD CONSTRAINT FK_7 FOREIGN KEY (ARCHIVO) REFERENCES CAT_ARCHIVO_TIPO(ID);
GO

-- DAT_ARCHIVOS_BIBLIA → DAT_APRENDIZAJE_BIBLIA
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_8')
ALTER TABLE DAT_ARCHIVOS_BIBLIA
ADD CONSTRAINT FK_8 FOREIGN KEY (MOVIMIENTO) REFERENCES DAT_APRENDIZAJE_BIBLIA(ID);
GO

-- DAT_ARCHIVOS_FINANZAS → CAT_ARCHIVO_TIPO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_9')
ALTER TABLE DAT_ARCHIVOS_FINANZAS
ADD CONSTRAINT FK_9 FOREIGN KEY (ARCHIVO) REFERENCES CAT_ARCHIVO_TIPO(ID);
GO

-- DAT_ARCHIVOS_FINANZAS → DAT_MOVIMIENTOS_FINANZAS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_10')
ALTER TABLE DAT_ARCHIVOS_FINANZAS
ADD CONSTRAINT FK_10 FOREIGN KEY (MOVIMIENTO) REFERENCES DAT_MOVIMIENTOS_FINANZAS(ID);
GO

-- DAT_ARCHIVOS_MEDICO → CAT_ARCHIVO_TIPO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_11')
ALTER TABLE DAT_ARCHIVOS_MEDICO
ADD CONSTRAINT FK_11 FOREIGN KEY (ARCHIVO) REFERENCES CAT_ARCHIVO_TIPO(ID);
GO

-- DAT_ARCHIVOS_MEDICO → DAT_CONSULTAS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_12')
ALTER TABLE DAT_ARCHIVOS_MEDICO
ADD CONSTRAINT FK_12 FOREIGN KEY (MOVIMIENTO) REFERENCES DAT_CONSULTAS_MEDICO(ID);
GO

-- DAT_CONSULTAS_MEDICO → CAT_EVENTOS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_13')
ALTER TABLE DAT_CONSULTAS_MEDICO
ADD CONSTRAINT FK_13 FOREIGN KEY (EVENTO) REFERENCES CAT_EVENTOS_MEDICO(ID);
GO

-- DAT_CONSULTAS_MEDICO → CAT_IMPORTANCIA_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_14')
ALTER TABLE DAT_CONSULTAS_MEDICO
ADD CONSTRAINT FK_14 FOREIGN KEY (IMPORTANCIA) REFERENCES CAT_IMPORTANCIA_MEDICO(ID);
GO

-- DAT_CONSULTAS_MEDICO → CAT_MODULOS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_15')
ALTER TABLE DAT_CONSULTAS_MEDICO
ADD CONSTRAINT FK_15 FOREIGN KEY (MODULO_ID) REFERENCES CAT_MODULOS(ID);
GO

-- DAT_CONSULTAS_MEDICO → CAT_CLINICAS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_16')
ALTER TABLE DAT_CONSULTAS_MEDICO
ADD CONSTRAINT FK_16 FOREIGN KEY (UNIDAD_MEDICA) REFERENCES CAT_CLINICAS_MEDICO(ID);
GO

-- DAT_MEDICAMENTOS_MEDICO → DAT_CONSULTAS_MEDICO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_17')
ALTER TABLE DAT_MEDICAMENTOS_MEDICO
ADD CONSTRAINT FK_17 FOREIGN KEY (CONSULTA) REFERENCES DAT_CONSULTAS_MEDICO(ID);
GO

-- DAT_MOVIMIENTOS_FINANZAS → CAT_CONCEPTOS_FINANZAS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_18')
ALTER TABLE DAT_MOVIMIENTOS_FINANZAS
ADD CONSTRAINT FK_18 FOREIGN KEY (CONCEPTO_ID) REFERENCES CAT_CONCEPTOS_FINANZAS(ID);
GO

-- DAT_MOVIMIENTOS_FINANZAS → CAT_MODULOS
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_19')
ALTER TABLE DAT_MOVIMIENTOS_FINANZAS
ADD CONSTRAINT FK_19 FOREIGN KEY (MODULO) REFERENCES CAT_MODULOS(ID);
GO

-- CAT_TIPOS → CAT_CAT
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_20')
ALTER TABLE CAT_TIPOS
ADD CONSTRAINT FK_20 FOREIGN KEY (CATEGORIA) REFERENCES CAT_CAT(ID);
GO

-- CAT_LIBROS_BIBLIA → BIBLIA 
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_21')
ALTER TABLE BIBLIA
ADD CONSTRAINT FK_21 FOREIGN KEY (LibroNum) REFERENCES CAT_LIBROS_BIBLIA(ID);
GO

-- CAT_LIBROS_BIBLIA → DAT_TAGS_BIBLIA 
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_22')
ALTER TABLE DAT_TAGS_BIBLIA
ADD CONSTRAINT FK_22 FOREIGN KEY (LIBRO_ID) REFERENCES CAT_LIBROS_BIBLIA(ID);
GO

-- CAT_TAGS_BIBLIA → DAT_TAGS_BIBLIA 
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_23')
ALTER TABLE DAT_TAGS_BIBLIA
ADD CONSTRAINT FK_23 FOREIGN KEY (TAG_ID) REFERENCES CAT_TAGS_BIBLIA(ID);
GO

-- CAT_TAGS_TIPO_BIBLIA → DAT_TAGS_BIBLIA 
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_24')
ALTER TABLE DAT_TAGS_BIBLIA
ADD CONSTRAINT FK_24 FOREIGN KEY (TAG_TIPO_ID) REFERENCES CAT_TAGS_TIPO_BIBLIA(ID);
GO



-- Consulta para verificar las relaciones de claves foráneas creadas
SELECT
    fk.name AS FK_Name,
    OBJECT_NAME(fk.parent_object_id) AS Tabla_Origen,
    c1.name AS Columna_Origen,
    OBJECT_NAME(fk.referenced_object_id) AS Tabla_Referencia,
    c2.name AS Columna_Referencia
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc 
    ON fk.object_id = fkc.constraint_object_id
JOIN sys.columns c1 
    ON fkc.parent_object_id = c1.object_id
   AND fkc.parent_column_id = c1.column_id
JOIN sys.columns c2
    ON fkc.referenced_object_id = c2.object_id
   AND fkc.referenced_column_id = c2.column_id
WHERE fk.name LIKE '%FK%'
ORDER BY fk.name;
