/* =========================================================
   TABLAS BOT TELEGRAM – SISTEMA DE TRABAJOS
   ========================================================= */


------------------------------------------------------------
-- BT_CLIENTES
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_CLIENTES'
)
CREATE TABLE BT_CLIENTES (
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(150) NOT NULL,
    TELEFONO NVARCHAR(30) NULL,
    CORREO NVARCHAR(150) NULL,
    OBSERVACIONES NVARCHAR(500) NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    ACTIVO BIT DEFAULT 1
);
GO


------------------------------------------------------------
-- BT_USUARIOS_TG
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_USUARIOS_TG'
)
CREATE TABLE BT_USUARIOS_TG (
    ID_USUARIO_TG BIGINT NOT NULL,
    ID_CLIENTE INT NULL,
    USERNAME NVARCHAR(100) NULL,
    NOMBRE NVARCHAR(100) NULL,
    APELLIDO NVARCHAR(100) NULL,
    TIPO_USUARIO NVARCHAR(20) NOT NULL DEFAULT 'CLIENTE',
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    ACTIVO BIT DEFAULT 1,

    CONSTRAINT PK_BT_USUARIOS_TG
        PRIMARY KEY (ID_USUARIO_TG)
);
GO


------------------------------------------------------------
-- BT_EQUIPOS
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_EQUIPOS'
)
CREATE TABLE BT_EQUIPOS (
    ID_EQUIPO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    TIPO NVARCHAR(50) NOT NULL,
    MARCA NVARCHAR(100) NULL,
    MODELO NVARCHAR(100) NULL,
    NUMERO_SERIE NVARCHAR(150) NULL,
    NOMBRE_EQUIPO NVARCHAR(100) NULL,
    OBSERVACIONES NVARCHAR(500) NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    ACTIVO BIT DEFAULT 1
);
GO


------------------------------------------------------------
-- BT_TRABAJOS
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_TRABAJOS'
)
CREATE TABLE BT_TRABAJOS (
    ID_TRABAJO INT IDENTITY(1,1) PRIMARY KEY,
    FOLIO NVARCHAR(30) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_EQUIPO INT NULL,

    TIPO_TRABAJO NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(500) NULL,

    OBSERVACIONES NVARCHAR(1000) NULL,
    REQUISITOS NVARCHAR(1000) NULL,

    ESTATUS NVARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',

    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    FECHA_TERMINADO DATETIME NULL,

    ACTIVO BIT DEFAULT 1,

    CONSTRAINT UQ_BT_TRABAJOS_FOLIO
        UNIQUE (FOLIO)
);
GO


------------------------------------------------------------
-- BT_TRABAJOS_CONCEPTOS
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_TRABAJOS_CONCEPTOS'
)
CREATE TABLE BT_TRABAJOS_CONCEPTOS (
    ID_CONCEPTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_TRABAJO INT NOT NULL,

    TIPO NVARCHAR(30) NOT NULL,
    DESCRIPCION NVARCHAR(255) NOT NULL,

    CANTIDAD DECIMAL(10,2) NOT NULL DEFAULT 1,
    COSTO DECIMAL(12,2) NOT NULL DEFAULT 0,
    PRECIO DECIMAL(12,2) NOT NULL DEFAULT 0,

    OBSERVACIONES NVARCHAR(500) NULL,

    ACTIVO BIT DEFAULT 1
);
GO


------------------------------------------------------------
-- BT_TRABAJOS_HISTORIAL
------------------------------------------------------------
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'BT_TRABAJOS_HISTORIAL'
)
CREATE TABLE BT_TRABAJOS_HISTORIAL (
    ID_HISTORIAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_TRABAJO INT NOT NULL,

    ESTATUS NVARCHAR(30) NOT NULL,
    DESCRIPCION NVARCHAR(1000) NULL,

    FECHA DATETIME DEFAULT GETDATE(),

    ID_USUARIO_TG BIGINT NULL
);
GO


/* =========================================================
   CONSTRAINTS (BT_#)
   ========================================================= */


-- BT_1 → USUARIOS TG → CLIENTES
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_1'
)
ALTER TABLE BT_USUARIOS_TG
ADD CONSTRAINT BT_1
FOREIGN KEY (ID_CLIENTE)
REFERENCES BT_CLIENTES(ID_CLIENTE);
GO


-- BT_2 → EQUIPOS → CLIENTES
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_2'
)
ALTER TABLE BT_EQUIPOS
ADD CONSTRAINT BT_2
FOREIGN KEY (ID_CLIENTE)
REFERENCES BT_CLIENTES(ID_CLIENTE);
GO


-- BT_3 → TRABAJOS → CLIENTES
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_3'
)
ALTER TABLE BT_TRABAJOS
ADD CONSTRAINT BT_3
FOREIGN KEY (ID_CLIENTE)
REFERENCES BT_CLIENTES(ID_CLIENTE);
GO


-- BT_4 → TRABAJOS → EQUIPOS
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_4'
)
ALTER TABLE BT_TRABAJOS
ADD CONSTRAINT BT_4
FOREIGN KEY (ID_EQUIPO)
REFERENCES BT_EQUIPOS(ID_EQUIPO);
GO


-- BT_5 → CONCEPTOS → TRABAJOS
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_5'
)
ALTER TABLE BT_TRABAJOS_CONCEPTOS
ADD CONSTRAINT BT_5
FOREIGN KEY (ID_TRABAJO)
REFERENCES BT_TRABAJOS(ID_TRABAJO);
GO


-- BT_6 → HISTORIAL → TRABAJOS
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_6'
)
ALTER TABLE BT_TRABAJOS_HISTORIAL
ADD CONSTRAINT BT_6
FOREIGN KEY (ID_TRABAJO)
REFERENCES BT_TRABAJOS(ID_TRABAJO);
GO


-- BT_7 → HISTORIAL → USUARIOS TG
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'BT_7'
)
ALTER TABLE BT_TRABAJOS_HISTORIAL
ADD CONSTRAINT BT_7
FOREIGN KEY (ID_USUARIO_TG)
REFERENCES BT_USUARIOS_TG(ID_USUARIO_TG);
GO